---
- name: Register Microsoft key and feed
  hosts: all
  become: yes
  tasks: 
    - name: Download the package 
      get_url:
       url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
       dest: /home/ansible
    - name: install the package
      dpkg_selections:
       name: packages-microsoft-prod.deb
       selection: install
    - name: install .net core runtime
      apt:
       name: 
        - apt-transport-https 
        - aspnetcore-runtime-3.1
       state: present
       update_cache: yes 
    - name: install nginx
      apt:
       name: nginx
       state: present
    - name: modify the config files
      copy: 
       src: F:\practice
       dest: /etc/nginx/sites-available/default
    - name: create a directory
      file:
        path: /var/www/nopCommerce440
        state: directory
        mode: 0755
    
    - name: Change the working directory to somedir/ and run the command as db_owner if /path/to/database does not exist.
      command: sudo wget https://github.com/nopSolutions/nopCommerce/releases/download/release-4.40.4/nopCommerce_4.40.4_NoSource_linux_x64.zip
       args:
        chdir: /var/www/nopCommerce440
        creates: /var/www/nopCommerce440      
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        enabled: yes
        state: restarted           
